spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: master
      # 严格匹配数据源,默认false.true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/mybatis_plus
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: lyh701721
        slave_1:
          url: jdbc:mysql://localhost:3306/mybatis_plus_1
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: lyh701721
server:
  port: 80
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #全局配置
  global-config:
    db-config:
      #设置实体类对应表的统一前缀
      table-prefix: t_
      #设置主键生成策略
      id-type: auto
  type-aliases-package: com.example.entity
  #扫描通用枚举
  type-enums-package: com.example.enums