spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: lyh701721
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
server:
  port: 80