spring:
  redis:
    host: localhost
    port: 6379
    database: 0 #??
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: lyh701721
    driver-class-name: com.mysql.cj.jdbc.Driver